name: GitHub Actions Build UAS-PCC-YANYANJ-2025
run-name: ${{ github.actor }} is Building Docker Image 🚀
on: [push]
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Verify Dockerfile exists
        run: ls -la
   
      - name: login and build
        run: |
          docker build -t yanyanjymv/uas-pcc-yanyanj-2025:latest -f Dockerfile .
          echo ${{ secrets.password }} | docker login -u ${{ secrets.username }} --password-stdin
          docker push yanyanjymv/uas-pcc-yanyanj-2025:latest